name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: .github/workflows/scripts/run_tests.sh

  Linters:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchains
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.3
        id: go
      - name: gcc
        run: |
          gcc --version
        shell: bash
      - name: Install linters
        run: go get github.com/bazelbuild/buildtools/buildifier
      - uses: actions/checkout@v2
      - name: C++ Build
        run: .github/workflows/scripts/build_cpp.sh
      - name: C++ linters
        run: .github/workflows/scripts/lint_cpp.sh
      - name: Bazel linters
        run: .github/workflows/scripts/lint_bazel.sh
      
